name: "Junit Report to Annotations"
description: "Create an annotation of the test run summaryand also list first n failed tests as seporate annotations"
branding:
  icon: "box"
  color: "green"
inputs:
  access-token:
    description: "github token"
    required: true
  path:
    description: "glob to junit xml files"
    required: true
    default: "**/TEST-*.xml"
  includeSummary:
    description: "include summary annotation"
    required: true
    default: true
  numFailures:
    description: "max number of failed tests to include"
    required: true
    default: 10
  name:
    description: "Name of the Check in the github actions UI"
    required: true
    default: "Junit Results"
  testJobName:
    description: "Name of the test job"
    required: true
    default: "Tests"
runs:
  using: "node12"
  main: "index.js"
